name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2
          - 3
        java:
          - 8
          - 11
          - 14
          - 16
    name: Scala v${{ matrix.scala }} / Java v${{ matrix.java }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1

      - name: Cache sbt
        uses: coursier/cache-action@v6

      - name: Build and test
        shell: bash
        run: bin/ci ${{ matrix.scala }}
