name: CI

on:
  pull_request:
  push:
    paths:
      - 'bin/**'
      - 'downstream-tests/**'
      - 'library/**'
    tags-ignore:
      - v*.*.*

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 14
            scala: 2
          - java: 8
            scala: 3
    name: Scala v${{ matrix.scala }} / Java v${{ matrix.java }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Build and test
        shell: bash
        run: bin/ci ${{ matrix.scala }}
